services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    ports:
      - 5433:5432
    networks:
      - api-network

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: authentication@api.com
      PGADMIN_DEFAULT_PASSWORD: sudosu
    ports:
      - 5051:80
    depends_on:
      - postgres
    networks:
      - api-network

networks:
  api-network:
    driver: bridge