services:
  postgres:
    image: postgres:latest
    container_name: ${DATABASE_HOST}
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    ports:
      - 5433:5432
    networks:
      - ecommerce-network

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: ${DATABASE_HOST}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5051:80
    depends_on:
      - postgres
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge