#
# Build stage
#
FROM maven:3.9.6-amazoncorretto-21 AS build

WORKDIR /Hackaton-Users

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B package -DskipTests

#
# Package stage
#
FROM amazoncorretto:21-alpine-jdk

WORKDIR /Hackaton-Users

COPY --from=build /Hackaton-Users/target/*.jar ./Hackaton-Users.jar

EXPOSE 7076

ENTRYPOINT ["java","-jar","Hackaton-Users.jar"]